from . import add_player
from . import set_tour_forecast
from . import change_match_forecast
from . import complement
from . import delete_user
from . import get_main_table
from . import get_my_forecast
from . import get_result_tour
from . import other_forecast
from . import reminder
from . import update